minimumReleaseAgeExclude:
  - '@stremio/*'

blockExoticSubdeps: false

patchedDependencies:
  '@stremio/stremio-video@0.0.98': patches/stremio_video_0_0_98.patch

overrides:
  qs: 6.16.0
  '@babel/runtime': 7.29.2
  shell-quote: 1.11.0
  websocket-driver: 0.7.5
  proxy-addr: 2.0.8
  'brace-expansion@^1.0.0': 1.1.20
  'brace-expansion@^2.0.0': 2.1.6
  browserslist: 4.28.7
  fast-uri: 3.1.8
  'js-yaml@^4.0.0': 4.3.2
  'nanoid@^3.0.0': 3.3.18
  postcss: 8.5.18
  source-map-js: 1.2.2
  svgo: 4.1.0
  ws: 8.21.0
  compression: 1.8.2
  'js-yaml@^3.0.0': 3.15.2
  'brace-expansion@^5.0.0': 5.0.11
  'serialize-javascript@^6.0.0': 7.0.5
  '@babel/plugin-transform-modules-systemjs': 7.29.4
